[["Item Attribute"]]
attribute_name = "Test Size"
priority = 1
[["Item Attribute".item_attribute_values]]
attribute_value = "Extra Small"
abbr = "XSL"

[["Item Attribute".item_attribute_values]]
attribute_value = "Small"
abbr = "S"

[["Item Attribute".item_attribute_values]]
attribute_value = "Medium"
abbr = "M"

[["Item Attribute".item_attribute_values]]
attribute_value = "Large"
abbr = "L"

[["Item Attribute".item_attribute_values]]
attribute_value = "Extra Large"
abbr = "XL"

[["Item Attribute".item_attribute_values]]
attribute_value = "2XL"
abbr = "2XL"


[["Item Attribute"]]
attribute_name = "Test Colour"
priority = 2
[["Item Attribute".item_attribute_values]]
attribute_value = "Red"
abbr = "R"

[["Item Attribute".item_attribute_values]]
attribute_value = "Green"
abbr = "G"

[["Item Attribute".item_attribute_values]]
attribute_value = "Blue"
abbr = "B"


