[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer With Template"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer P"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer 1"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer 2"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer 3"
customer_type = "Individual"
territory = "_Test Territory"

[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer USD"
customer_type = "Individual"
territory = "_Test Territory"
default_currency = "USD"
[[Customer.accounts]]
company = "_Test Company"
account = "_Test Receivable USD - _TC"


[[Customer]]
customer_group = "_Test Customer Group"
customer_name = "_Test Customer With Tax Category"
customer_type = "Individual"
territory = "_Test Territory"
tax_category = "_Test Tax Category 1"

