[["Product Bundle"]]
new_item_code = "_Test Product Bundle Item"
[["Product Bundle".items]]
doctype = "Product Bundle Item"
item_code = "_Test Item"
parentfield = "items"
qty = 5.0

[["Product Bundle".items]]
doctype = "Product Bundle Item"
item_code = "_Test Item Home Desktop 100"
parentfield = "items"
qty = 2.0


