[[Shareholder]]
naming_series = "SH-"
title = "Iron Man"
company = "_Test Company"

[[Shareholder]]
naming_series = "SH-"
title = "Thor"
company = "_Test Company"

[[Shareholder]]
naming_series = "SH-"
title = "Hulk"
company = "_Test Company"

